### ISSUE TITLE
패키지 설치 오류

### ISSUE THREAD

**Issue by nwaistd** [VeranosTech/vopt.conda#2]
```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 819, in __call__
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 11, in execute
    install(args, parser, 'install')
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 253, in install
    handle_txn(unlink_link_transaction, prefix, args, newenv)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 278, in handle_txn
    unlink_link_transaction.download_and_extract()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 174, in download_and_extract
    self._pfe.execute()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/conda/core/package_cache_data.py", line 605, in execute
    raise CondaMultiError(exceptions)
conda.CondaMultiError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/anaconda/linux-64/openblas-devel-0.2.20-7.tar.bz2>
Elapsed: 00:00.856117
CF-RAY: 46124653a803a197-ICN

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

HTTP 404 NOT FOUND for url <https://conda.anaconda.org/anaconda/linux-64/pyqt-5.9.2-py36h22d08a2_1.tar.bz2>
Elapsed: 00:00.897353
CF-RAY: 461246591c58a215-ICN

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

anaconda 채널에서 패키지에서 설치 시 계속해서 url 에러가 발생합니다.
url에 접속해보면 실제로 파일이 없습니다.
개별 패키지를 따로 설치하면 정상적인 url에서 패키지를 받아오는데(예, pyqt만 설치를 할 때는 정상적으로 다운로드 가능) 패키지 리스트 파일에 있는 패키지들을 한 번에 설치할 때는 의존성 문제 때문인지 정상적이지 않은 url에서 다운로드를 시도하다가 에러가 발생합니다. 
conda-forge 채널까지는 오늘 시도해보지 않았는데 어제는 conda-forge 채널도 같은 에러가 반복되었던 것으로 기억합니다.

**Comment by nwaistd** [comment]
버전과 빌드를 지정해서 설치
