### ISSUE TITLE
install_pkg.sh 실행 오류

### ISSUE THREAD

**Issue by nwaistd** [VeranosTech/vopt.conda#31]
해당 파일에서 
pip install git+https://github.com/VeranosTech/CyLP.git@py3 실행 시 아래와 같은 오류가 발생합니다.

CyLP package for Python3 installing...
Collecting git+https://github.com/VeranosTech/CyLP.git@py3
  Cloning https://github.com/VeranosTech/CyLP.git (to py3) to /tmp/pip-_w1sc0qz-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-_w1sc0qz-build/setup.py", line 370, in <module>
        s_README = getBdistFriendlyString(open('README.rst').read())
      File "/anaconda3/envs/vopt/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 343: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-_w1sc0qz-build/

**Comment by nwaistd** [comment]
EC2 인스턴스에서 root 유저가 아닌 ubuntu 유저로 설치 시 정상적으로 작동합니다.
